### PR TITLE
Add support for DC/OS version 2.0

### PR DESCRIPTION
**Pull request by kaiwalyajoshi**

### CODE REVIEW

**Comment by porridge** [comment]
I think this also at least needs a Dockerfile change, but I'll let @VladimirKravtsov speak.
Also, the version is bumped separately, at release time.

**Comment by mpereira** [comment]
@porridge does it make sense to be optimistic with which newer DC/OS versions this script is compatible with? i.e. only make it incompatible with versions that we **know don't work** (1.10).

**Comment by porridge** [comment]
> @porridge does it make sense to be optimistic with which newer DC/OS versions this script is compatible with? i.e. only make it incompatible with versions that we **know don't work** (1.10).

I don't think so, because we need a specific CLI plugin (see `Dockerfile`).

**Comment by mpereira** [comment]
Ah, right.

**Comment by kaiwalyajoshi** [comment]
Closing this in favour of #22

**Pull request closed without merging**
